### ISSUE TITLE
I'm getting an error with v1.2

### ISSUE THREAD

**Issue by lenamtl** [chiriboga/SPemail#2]
Hi,

I'm using 1.1 version and it is working ok.

Now I'm trying the 1.2 version and I'm getting an error:
Uncaught SyntaxError: Unexpected string  on line 58
 case "plainbase""mailbase":
Uncaught TypeError: $(...).spemail is not a function 

I'm using this example
 $('#email').spemail('|,:','mailbase');
 <span id="email">yourname|yourcompany:net</span>	

Thanks

**Comment by chiriboga** [comment]
Hi! thanks for the heads up. I totally messed that up, but now it should be fixed! thanks for using the code. let me know if there's anything else.

**Comment by chiriboga** [comment]
actually let me know and you close this, unless i have to.

**Comment by lenamtl** [comment]
Hi,
Thanks
I have tested all 3 types and this is working fine.

Don't forget to to rename the script to reflect the appropriate version
or remove the version from the name :)

**Comment by chiriboga** [comment]
thanks... just did that too.. I will close this error now.
